### ISSUE TITLE
Provide correct VIN_CHECK_URL value for the .env file

### ISSUE THREAD

**Issue by mpagels** [DanielBojorquezf/vin-decoder-api#1]
The current value for the `VIN_CHECK_URL` key in the README is confusing.

The user needs the correct value to insert. Because the puppeteer library is used to find specific buttons on a website.
So it has to be the website puppeteer is looking for a button with the id `#btnSubmit`.

PLS provide the URL for VIN_CHECK_URL or, at least tell everyone, on which website the scrapper can be used.

**Comment by DanielBojorquezf** [comment]
Hi, 

Sorry for the late response! This is the vin check url: `https://vpic.nhtsa.dot.gov/decoder`

I'll add it in the .env-example.

Thanks!
